[build]
  command = "npx expo export --platform web --output-dir dist && cp -R dist/client/_expo dist/server/_expo || true && cp -R dist/client/assets dist/server/assets || true && cp dist/client/favicon.ico dist/server/favicon.ico || true"
  publish = "dist/server"
  functions = "dist/server/_expo/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/courses/*"
  to = "/courses/[id].html"
  status = 200

[[redirects]]
  from = "/module/*"
  to = "/module/[id].html"
  status = 200

[[redirects]]
  from = "/_sitemap"
  to = "/_sitemap.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200


