export { supabase, handleSupabaseError, getPaginationRange } from './client';
export type {
  Database,
  ApiResponse,
  PaginationParams,
  PaginatedResponse,
  DbResult,
  DbResultOk,
  Tables,
  InsertTables,
  UpdateTables,
  Company,
  Course,
  Module,
  Lesson,
  Slide,
  SlideAiPrompt,
  User,
  CompanyMember,
  CompanyCourse,
  Criteria,
  UserCriteriaRating,
  UserModuleProgress,
  UserSlideInteraction,
} from './client';
